---
title: "7_survival_analysis_os"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Generated on: `r Sys.time()`

Import required packages
```{r}
library(tidyverse)
library(survival)
library(survminer)
```

```{r}
workDir <- "/home/bibu/Workspace/crlm_cohort/"

clinPatAnnotFn <- paste(workDir, "output/clin_data_annot.csv", sep="")
```

Import data
```{r}
clinPatAnnotData <- read.csv(clinPatAnnotFn)

clinPatAnnotData$marginal0 <- fct_relevel(clinPatAnnotData$marginal0, "0", ">0")
clinPatAnnotData$marginal01 <- fct_relevel(clinPatAnnotData$marginal01, "0", "<1", "1+")
clinPatAnnotData$desmo10050 <- fct_relevel(clinPatAnnotData$desmo10050, "0-50", "50-100", "100")

# IMPORTANT to uncomment according to desired analysis
#survival_type <- "OS" # Overall survival
survival_type <- "PFS" # Progression free survival
if(!(survival_type %in% c("OS", "PFS"))) {
  stop(paste("Wrong survival type: ", survival_type))
}

# IMPORTANT to uncomment according to desired analysis
#cohort_type <- "All"
#cohort_type <- "Neoadjuvant"
cohort_type <- "Chemonaive"
if(cohort_type == "Neoadjuvant") {
  clinPatAnnotData <- clinPatAnnotData %>% filter(neoadjuvant == "Y")
} else if(cohort_type == "Chemonaive") {
  clinPatAnnotData <- clinPatAnnotData %>% filter(neoadjuvant == "N")
} else if(cohort_type != "All") {
  stop(paste("Wrong cohort type: ", cohort_type))
}
```

Parametrized survival function (to avoid code repetition)
```{r}
# Adapted from https://stackoverflow.com/questions/51193443/creating-a-function-passing-its-arguments-to-the-surv-function-or-any-other
survFun <- function(surv.object, grouping, fun.dat) {
  params <- list(surv.object = substitute(surv.object), grouping = substitute(grouping), fun.dat = substitute(fun.dat))
  expr <- substitute(survfit(surv.object ~ grouping, data = fun.dat), params)
  fit.dat <- eval.parent(expr)
  
p <- ggsurvplot(fit.dat, data = fun.dat, 
    title = paste(survival_type,"-", cohort_type, "patients"),
    xlab = "Days", 
    ylab = "Survival probability",
    pval = TRUE)  

  print(fit.dat)
  print(p)
  print(summary(fit.dat))
  
 }
```

Survival analysis clinica data (Overall Survival)
```{r}
# https://www.datacamp.com/community/tutorials/survival-analysis-R
# https://rviews.rstudio.com/2017/09/25/survival-analysis-with-r/
# https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html

# Fit survival data using the Kaplan-Meier method
#survObjectOS <- Surv(time = clinPatAnnotData$time_fu_os, event = clinPatAnnotData$status_fu_os) # OS
if(survival_type == "OS") {
  survObjectOS <- Surv(time = clinPatAnnotData$time_fu_os, event = clinPatAnnotData$status_fu_os)
} else if(survival_type == "PFS") {
  survObjectOS <- Surv(time = clinPatAnnotData$time_fu_prog, event = clinPatAnnotData$status_fu_prog)
}
#survObjectOS <- Surv(time = ifelse(survival_type == "OS", clinPatAnnotData$time_fu_os, clinPatAnnotData$time_fu_prog), 
#                     event = ifelse(survival_type == "OS", clinPatAnnotData$status_fu_os, clinPatAnnotData$status_fu_prog))
survObjectOS

# Overall
survFun(survObjectOS, 1, clinPatAnnotData)

# Age
survFun(survObjectOS, age_, clinPatAnnotData)

# Sex
survFun(survObjectOS, sex, clinPatAnnotData)

# Primary side
survFun(survObjectOS, primary_side, clinPatAnnotData)

# Sync/meta
survFun(survObjectOS, sync_meta, clinPatAnnotData)

# Neoadjuvant
survFun(survObjectOS, neoadjuvant, clinPatAnnotData)

# Num tumors
survFun(survObjectOS, num_tumors_, clinPatAnnotData)

# Largest tumor diameter
survFun(survObjectOS, max_tum_diameter, clinPatAnnotData)

# Sum of tumor diameters
survFun(survObjectOS, sum_tum_diameter, clinPatAnnotData)

# Marginal 0 mm
survFun(survObjectOS, marginal0, clinPatAnnotData)

# Marginal 1 mm
survFun(survObjectOS, marginal1, clinPatAnnotData)

# Marginal 0, 1 mm
survFun(survObjectOS, marginal01, clinPatAnnotData)

# Tumor percent (Blazer classification) according to original pathology report or completed by review when missing
survFun(survObjectOS, tum_percent_report, clinPatAnnotData)

# Tumor percent (Blazer classification), according to annotations (review)
survFun(survObjectOS, tum_percent_annot_, clinPatAnnotData)

# Predominant GP (D, R, P)
survFun(survObjectOS, gp_predo3, clinPatAnnotData)
survFun(survObjectOS, gp_predo4, clinPatAnnotData)

# Predominant GP (D, R)
clinPatAnnotDataNoP <- filter(clinPatAnnotData, gp_predo3 != 'P')
if(survival_type == "OS") {
  survObjectOSNoP <- Surv(time = clinPatAnnotDataNoP$time_fu_os, event = clinPatAnnotDataNoP$status_fu_os)
} else if(survival_type == "PFS") {
  survObjectOSNoP <- Surv(time = clinPatAnnotDataNoP$time_fu_prog, event = clinPatAnnotDataNoP$status_fu_prog)
}
survFun(survObjectOSNoP, gp_predo3, clinPatAnnotDataNoP)

# Replacement GP, according to annotations
survFun(survObjectOS, replacement, clinPatAnnotData)

# Desmo GP, according to annotations
survFun(survObjectOS, desmo95, clinPatAnnotData)
survFun(survObjectOS, desmo10050, clinPatAnnotData)
```

Experimental parameters
```{r}
# Summmed tumor score, calculated as the sum of % tumor cells x diameter, the former according to original pathology report or completed by review when missing
survFun(survObjectOS, tum_score_report, clinPatAnnotData)

# Summmed tumor score, calculated as the sum of % tumor cells x diameter, the former according to annotations (review)
survFun(survObjectOS, tum_score_annot_, clinPatAnnotData)

# Summmed replacement score, calculated as the sum of % replacement x diameter, the former according to annotations (review)
survFun(survObjectOS, replacement_score, clinPatAnnotData)

# % Replacement 2 vs 1 (for cases with replacement)
survFun(survObjectOS, r2_group, clinPatAnnotData)
```

Multivariate analysis (CCox proportional hazards model)
```{r, fig.width= 10}
# Fit a Cox proportional hazards model
# TODO: Study how this works and what parameter should be included
# OS All fit.coxph <- coxph(survObjectOS ~ age + num_tumors_ + max_tum_diameter + marginal01 + desmo95 + tum_score_annot_,
# OS Neoadj fit.coxph <- coxph(survObjectOS ~ age + num_tumors_ + max_tum_diameter + marginal01 + gp_predo3 + tum_score_annot_,
# OS Chemonaive fit.coxph <- coxph(survObjectOS ~ age + num_tumors_ + max_tum_diameter + tum_score_report,
# PFS All fit.coxph <- coxph(survObjectOS ~ age + sum_tum_diameter + marginal1 + desmo95 + tum_score_annot_,
# PFS Neoadj
fit.coxph <- coxph(survObjectOS ~ age + gp_predo3,
                   data = clinPatAnnotData)
ggforest(fit.coxph, data = clinPatAnnotData)
```

Relevant case series
```{r}
untreated <- clinPatAnnotData %>% filter(neoadjuvant == "N") %>% arrange(desc(desmo_percent))
head(select(untreated, id, desmo_percent, time_fu_os, status_fu_os), n= 8)

treated <- clinPatAnnotData %>% filter(neoadjuvant == "Y") %>% arrange(desc(desmo_percent))
head(select(treated, id, desmo_percent, time_fu_os, status_fu_os), n= 16)
```